### ISSUE TITLE
No Rendering in the frontend

### ISSUE THREAD

**Issue by mediamr** [nvidoni/MarkupYahooWeather#2]
Since a short time the weather widget doesn't render weather data. There is no error in the console. Changing the location seems to have no effect. Any idea? Andreas

**Comment by nvidoni** [comment]
I haven't looked and revised the code for quite some time now, maybe Yahoo changed something in their weather API... I'll take a look when I'll have some spare time.

**Comment by nvidoni** [comment]
I've changed API URL, 4 days ago Yahoo changed the URL for retrieving forecasts. See commited change...

**Comment by mediamr** [comment]
Cool, thank you for the super fast fix. Pushing this version also in the processwire module center would be nice.

**Comment by nvidoni** [comment]
Hi Andreas,

no problem :)

Bumped version ond github, updated the module in PW module repo and updated the post in PW forum ;)

Cheers
Nikola

**Comment by mediamr** [comment]
Top Support. Have a nice day! Andreas

**Comment by mediamr** [comment]
Hello Nikola, the Problem is there again. Can you have a look? Andreas

**Comment by Dzonny** [comment]
Any solution for this, it won't work anymore, or I'm not seeing the problem here?
